defaults:
  - finetune

handler: UNDIALBoost2ndBest # corresponds to the class defined in src/trainer/unlearn/undial_boost2ndBest.py
args: # HuggingFace TrainingArguments
  learning_rate: 1e-4
  num_train_epochs: 10
method_args: # Your own method-specific arguments
  gamma: 1.0
  alpha: 0.0
  beta: 10.0 # the strength of suppression on ground-truth tokens
  delta: 5.0 # the strength of boosting for 2nd-best alternative tokens (0.0 disables boosting)
  retain_loss_type: NLL